FROM node:20-alpine

WORKDIR /app

# Copia apenas os arquivos de dependências primeiro (aproveita cache do Docker)
COPY package.json package-lock.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
